name: Deploy Angular project

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular project
        run: ng build

      - name: Deploy to my-private-repo repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          repository: Ftohtarek/staging-wasta
          publish_dir: dist
          branch: staging
          force_orphan: true
