name: Deploy Angular project
run-name: ${{ github.actor }} is build and deploy wasta demo

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build

      - name: Deploy to my-private-repo repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          repository: ftohtarek/demo-wasta
          publish_dir: dist/wasta
          branch: gh-pages
          force_orphan: true
